import { careerUnits } from '../../data/careerData.js';
import { careerFormFields } from './careerForm.js';
import { sietHudHeader } from '../../components/common/HudHeader.js';
import { icon } from '../../components/common/SvgIcons.js';

export function careersPage() {
  const unit = careerUnits.college;
  return `<main class="careers-page">${sietHudHeader('Careers', 'Careers', false)}<section class="career-main"><div class="career-switcher"><div class="career-switcher-caption"><span>FIND YOUR PLACE</span><p>Three pathways. One shared purpose.</p></div><div class="career-tabs career-toggle" role="group" aria-label="Choose your career institution" style="--career-index: 0"><span class="career-toggle-track" aria-hidden="true"></span>${[['college', 'Engineering College', 'Inspire innovators', 'grad'], ['school', 'CBSE School', 'Shape young minds', 'industry'], ['lab', 'Food Testing Lab', 'Advance discovery', 'lab']].map(([key, label, caption, symbol], index) => `<button class="${index === 0 ? 'active' : ''}" data-unit="${key}" type="button" aria-pressed="${index === 0}"><span class="career-toggle-icon" aria-hidden="true">${symbol === 'lab' ? '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M9 3h6M10 3v7l-6 9a1.3 1.3 0 0 0 1 2h14a1.3 1.3 0 0 0 1-2l-6-9V3M7 15h10"/><path d="M10 18h.01M14 17h.01"/></svg>' : icon(symbol)}</span><span class="career-toggle-copy"><strong>${label}</strong><small>${caption}</small></span><span class="career-toggle-dot" aria-hidden="true"></span></button>`).join('')}</div></div><div class="career-intro career-institution-banner"><div class="career-institution-logo"><img src="${unit.logo}" alt="${unit.heading} logo"></div><div class="career-institution-copy"><h2>${unit.heading}</h2><p>${unit.desc}</p></div></div><div class="career-application-layout"><form class="career-form js-form"><div class="career-form-head"><small>APPLICATION FORM</small><h2>Faculty &amp; Professional Recruitment</h2></div><div class="career-fields">${careerFormFields(unit)}</div><button class="career-submit" type="submit">Submit Application →</button><p class="status" aria-live="polite"></p></form><aside class="career-categories"><div class="career-side-title"><small>EXPLORE OPENINGS</small><h2>Application Categories</h2></div>${unit.cats.map((c, i) => `<details ${i === 0 ? 'open' : ''}><summary>${c[0]} ${icon('down')}</summary><div>${c[2] ? `<p>${c[2]}</p>` : ''}${c[1].map(r => `<span>⇒ ${r}</span>`).join('')}</div></details>`).join('')}<div class="career-contact"><small>RECRUITMENT QUERIES</small><h3>Let’s build the future together.</h3><a href="mailto:careers@siet.ac.in">careers@siet.ac.in</a></div></aside></div></section></main>`;
}

